---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: default
spec:
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - securityContext:
            privileged: true
        - name: nifi
          image: passivedapp/apache-nifi-s3
          ports:
            - name: https
              containerPort: 8443
          env:
            - name: SINGLE_USER_CREDENTIALS_USERNAME
              value: admin
            - name: SINGLE_USER_CREDENTIALS_PASSWORD
              value: "<default-password-for-admin>"
            - name: NIFI_WEB_HTTPS_PORT
              value: '8443'
            - name: ACCESS_KEY
              value: "<bucket-access-key>"
            - name: SECRET_KEY
              value: "<bucket-secret-key>"
            - name: BUCKET_NAME
              value: "<your-bucket-name>"
            - name: S3_URL
              value: https://s3.fr-par.scw.cloud
            - name: S3_REGION
              value: fr-par
