---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: default
spec:
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - securityContext:
            privileged: true
        - name: nifi
          image: passivedapp/apache-nifi-s3
          ports:
            - name: https
              containerPort: 8443
          envFrom:
            - configMapRef:
                name: nifi-config
