name: Create apache-nifi-s3 docker container

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master

jobs:
  build-docker:
    env:
      CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.CI_REGISTRY_USER }}" --password-stdin
      - run: echo $(printf '{"commit_sha":"'"${CI_COMMIT_SHA}"'","'"commit_short_sha"'":"'"${CI_COMMIT_SHORT_SHA}"'","'"commit_ref_name"'":"'"${CI_COMMIT_REF_NAME}"'","'"commit_tag"'":"'"${CI_COMMIT_TAG}"'","'"pipeline_id"'":"'"${CI_PIPELINE_ID}"'","'"pipeline_iid"'":"'"${CI_PIPELINE_IID}"'","'"job_id"'":"'"${CI_JOB_ID}"'","'"project_name"'":"'"${CI_PROJECT_NAME}"'"}') > buildinfo.json
      - run: docker build -m 8g -t passivedapp/apache-nifi-s3 -f Dockerfile .
      - run: docker push passivedapp/apache-nifi-s3
